### ISSUE TITLE
Making this repository a Template

### ISSUE THREAD

**Issue by TheNeikos** [dontlaugh/rocket-yew-starter-pack#14]
On Github you can make a repository a template by going to Settings > "Template Repository"

This way people could easy use your repository to start their own!

**Comment by dontlaugh** [comment]
Hey this is a great idea. Easier than forking.

**Comment by dontlaugh** [comment]
I think this is done? Checked the templates box in settings. Reopen if needed.

**Comment by TheNeikos** [comment]
Yup, all working!
